name: Test on master branch

on:
  push:
    branches:
    - devel

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone sub repos
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        git submodule init
        git submodule update
    - name: Print env
      run: echo $GITHUB_ACTOR
    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
        gpg --import --batch ~/.gnupg/private.key
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Build and test ar4k-agent-web with gradle
      run: ./gradlew :ar4k-agent-web:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-agent-druido with gradle
      run: ./gradlew :ar4k-agent-druido:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-agent-small with gradle
      run: ./gradlew :ar4k-agent-small:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-agent-qa with gradle
      run: ./gradlew :ar4k-agent-qa:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-core with gradle
      run: ./gradlew :ar4k-core:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-seed with gradle
      run: ./gradlew :ar4k-seed:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-hazelcast with gradle
      run: ./gradlew :ar4k-hazelcast:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-activemq with gradle
      run: ./gradlew :ar4k-activemq:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-terminal with gradle
      run: ./gradlew :ar4k-terminal:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-serial-comm with gradle
      run: ./gradlew :ar4k-serial-comm:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-video with gradle
      run: ./gradlew :ar4k-video:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-pcap with gradle
      run: ./gradlew :ar4k-pcap:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-industrial with gradle
      run: ./gradlew :ar4k-industrial:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-ai with gradle
      run: ./gradlew :ar4k-ai:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-ai-nlp with gradle
      run: ./gradlew :ar4k-ai-nlp:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-kettle with gradle
      run: ./gradlew :ar4k-kettle:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
    - name: Build and test ar4k-vaadin with gradle
      run: ./gradlew :ar4k-vaadin:test -Dorg.gradle.daemon=false -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Psigning.keyId=F6113733 -Psigning.secretKeyRingFile=/home/runner/.gnupg/private.key --stacktrace
